apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: prod
data:
  TOKEN_EXPIRE: "2562000"
  NODE_ENV: "production"
  PORT: "9000"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: prod
data:
  REACT_APP_API_URL: "https://prod.ecomp.codes"