
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: prod
type: Opaque
stringData:
  DB_URL: jdbc:mysql://mysql:3306/gestionretour?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
  DB_USERNAME: appuser
  DB_PASSWORD: apppass123
  JWT_SECRET: aVeryLongSecureJwtSecretKeyThatIsAtLeast32CharactersLong

---
apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
  namespace: prod
type: Opaque
stringData:
  VITE_API_URL: "https://spring.ecomp.codes/api"


